# -*- coding: utf-8 -*-
"""number division python .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16dOR3eMY9AvpgrZ5qdL-cbAZH5LxDL_y
"""

#Question number 1:
n=int(input())
m=str(n)
if n%3==0 or '3' in m:
    print("Jugs")
elif n%5==0 or '5' in m:
    print("Mugs")
elif n%7==0 or '7' in m:
    print("Pugs")
else:
    print(n)